### ISSUE TITLE
[BUG] Inconsistent r-speedglm version numbering: 0.3_5 instead 0.3.5

### ISSUE THREAD

**Issue by brianmsm** [BioArchLinux/Packages#152]
This is not an error directly associated with installing the package from the command line. However, the PKGBUILD configuration file does not follow the usual coding of `_pkgver` to request download on CRAN and `pkgver` to publish to repository so the versioning follows the archlinux guideline: https://wiki.archlinux.org/title/Arch_package_guidelines#Package_versioning

I see that in a previous commit those variables were removed to use only `pkgver`, although I'm not sure why: https://github.com/BioArchLinux/Packages/commit/25888a1562768071d2f56b39c5b05b5485dac1b2

All other packages in this repository follow this proper versioning practice, e.g.: https://github.com/BioArchLinux/Packages/blob/master/BioArchLinux/r-lavaan/PKGBUILD

**Desktop:**
 - Desktop Enviroment: KDE
 - Linux Kernel: 6.3.8-zen1-1-zen
 - Package Version: speedglm 0.3_5 

**Additional context**
Just to complement. Currently, `speedglm` versioning causes a conflict when trying to install under the `bspm` package: https://github.com/Enchufa2/bspm/issues/71

**Comment by pekkarr** [comment]
Thanks for reporting, it should get fixed when the package gets rebuilt in about an hour

**Comment by sukanka** [comment]
@pekkarr plz note that according to arch wiki, dash in pkgver should be replaced with underscore instead of dot. see
https://wiki.archlinux.org/title/PKGBUILD#pkgver

**Comment by sukanka** [comment]
I suggest using underscore as we can get a one-to-one mapping between the R pkg version and pkgver in PKGBUILD.
colon can be replace with another symbol such as + (but this is not semantic.)

> Also almost all R packages in this repo and in AUR use dot as the replacement.

Maybe they are all wrong? Most of them are maintained by us.

**Comment by pekkarr** [comment]
Apparently colons aren't allowed in R package versions, as the [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file) guide states that

> The mandatory ‘Version’ field gives the version of the package. This is a sequence of at least two (and usually three) non-negative integers separated by single ‘.’ or ‘-’ characters.

I also checked all packages in CRAN and Bioconductor, and none of them have a colon in version. So there's no need to have colon replacing code after all.

> we can get a one-to-one mapping between the R pkg version and pkgver in PKGBUILD

What is the use case for this? Why would this be needed?

> Maybe they are all wrong?

I don't think using either is wrong. The R package guidelines allow both, but for consistency we should choose one and use that in all R packages.

> Most of them are maintained by us.

Even for the packages not maintained by us replacing with dot is far more common. I don't remember seeing any R package on AUR that uses underscore (except `r-speedglm`), probably because the [templates in R package guidelines](https://wiki.archlinux.org/title/R_package_guidelines#Build_and_Package) all use dot as the replacement.

> I'd like to add some examples from official repo

Yeah, it seems that underscores are commonly used for replacing hyphens. However, dots are used too for that purpose. The most notable example of this is the official `r` package, that [replaces hyphens in bundled R packages' versions with a dot](https://gitlab.archlinux.org/archlinux/packaging/packages/r/-/blob/4e8a82e6315b1630a940e9fbc9c86e16812f2b76/PKGBUILD#L95) when adding them to its `provides` array.

However, if we do decide to use underscores instead, that should be changed in all maintained R packages. Also the colon replacing code should be removed, probably at the same time if we switch to underscores.

**Comment by sukanka** [comment]
Ok. Since the template in R packages guideline use dot for both hyphens and colon, let's keep this convention.

> The most notable example of this is the official r package, that replaces hyphens in bundled R packages' versions with a dot when adding them to its provides array.

I have to mention that it is proposed by me. 
https://bugs.archlinux.org/task/74850
So this does not persuade me.

But the template does.

**Comment by pekkarr** [comment]
Let's keep using dots then.

However, the R package guidelines aren't that accurate. They claim that upstream R package versions can contain colons, which is false. They also say to put packages in the `LinkingTo` field to `depends`, even though those should really go to `makedepends` (unless they're also in `Depends` or `Imports`).

**Comment by starsareintherose** [comment]
Should this issue be closed?
